use_frameworks!

platform :ios, '8.0'

target 'ADCategoriesNew_Example' do
  pod 'ADCategoriesNew', :path => '../'

  target 'ADCategoriesNew_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
